version: 1.0.{build}
environment:
  connectionstrings:eventstore: Server=(local)\SQL2016;Database=eventstore;User ID=sa;Password=Password12!
services: mssql2016
build_script:
- ps: dotnet build .\Brickweave.sln
test_script:
- ps: scripts\test.ps1