// <auto-generated />
using System;
using AdvancedCqrs.CommandQueue.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvancedCqrs.CommandQueue.SqlServer.Migrations
{
    [DbContext(typeof(CommandQueueDbContext))]
    [Migration("20211028195930_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SeparateCommandQueue")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Brickweave.Cqrs.SqlServer.Entities.CommandQueueData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimsPrincipalJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CommandQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
